#!/usr/bin/env bash
set -euo pipefail

# upload-image.sh - Build and upload NixOS disk image to Hetzner Cloud
#
# Prerequisites:
#   - HCLOUD_TOKEN environment variable set
#   - nix with flakes enabled
#   - hcloud-upload-image tool (available in dev shell)
#
# Usage:
#   ./scripts/upload-image.sh [--architecture x86_64-linux|aarch64-linux]

ARCH="${1:-x86_64-linux}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
TFVARS_FILE="$PROJECT_ROOT/setup/terraform.tfvars"
TFVARS_EXAMPLE="$PROJECT_ROOT/setup/terraform.tfvars.example"

# Map Nix architecture to Hetzner architecture
case "$ARCH" in
  x86_64-linux)
    HCLOUD_ARCH="x86"
    ;;
  aarch64-linux)
    HCLOUD_ARCH="arm"
    ;;
  *)
    echo "Error: Unknown architecture $ARCH"
    echo "Supported: x86_64-linux, aarch64-linux"
    exit 1
    ;;
esac

# Check for HCLOUD_TOKEN
if [[ -z "${HCLOUD_TOKEN:-}" ]]; then
  echo "Error: HCLOUD_TOKEN environment variable is required"
  exit 1
fi

echo "==> Building disk image for $ARCH from github:outskirtslabs/nixos-hetzner..."
cd "$PROJECT_ROOT"
nix build "github:outskirtslabs/nixos-hetzner#diskImages.$ARCH.hetzner" --print-build-logs

IMAGE_PATH=$(find result -name '*.raw' -o -name '*.img' | head -1)
if [[ -z "$IMAGE_PATH" ]]; then
  echo "Error: Could not find built image in result/"
  exit 1
fi
IMAGE_PATH="$(readlink -f "$IMAGE_PATH")"
echo "==> Built image: $IMAGE_PATH"

# Generate description with timestamp
TIMESTAMP=$(date -u +%Y%m%d-%H%M%S)
DESCRIPTION="nixos-hetzner-demo-${TIMESTAMP}"

echo "==> Uploading image to Hetzner Cloud..."
echo "    Architecture: $HCLOUD_ARCH"
echo "    Description: $DESCRIPTION"

# Upload and capture output
OUTPUT=$(hcloud-upload-image upload \
  --image-path="$IMAGE_PATH" \
  --architecture="$HCLOUD_ARCH" \
  --description="$DESCRIPTION" 2>&1) || {
    echo "Error: Upload failed"
    echo "$OUTPUT"
    exit 1
  }

echo "$OUTPUT"

# Extract image ID from output (hcloud-upload-image prints "image=<id>")
IMAGE_ID=$(echo "$OUTPUT" | grep -oP 'image=\K\d+' | head -1 || true)

if [[ -z "$IMAGE_ID" ]]; then
  # Try alternate format
  IMAGE_ID=$(echo "$OUTPUT" | grep -oP 'ID:\s*\K\d+' | head -1 || true)
fi

if [[ -z "$IMAGE_ID" ]]; then
  echo ""
  echo "Warning: Could not automatically extract image ID from output"
  echo "Please check the output above for the image ID and manually update:"
  echo "  $TFVARS_FILE"
  exit 0
fi

echo ""
echo "==> Success! Image uploaded with ID: $IMAGE_ID"

# Update or create terraform.tfvars
update_tfvars() {
  local image_id="$1"
  local tfvars="$2"

  if [[ -f "$tfvars" ]]; then
    # File exists - update or add hcloud_image_id
    if grep -q '^[[:space:]]*#*[[:space:]]*hcloud_image_id' "$tfvars"; then
      # Line exists (commented or not) - replace it
      sed -i "s/^[[:space:]]*#*[[:space:]]*hcloud_image_id.*/hcloud_image_id = $image_id/" "$tfvars"
      echo "==> Updated hcloud_image_id in $tfvars"
    else
      # Line doesn't exist - add it after the header comment
      sed -i "1a hcloud_image_id = $image_id" "$tfvars"
      echo "==> Added hcloud_image_id to $tfvars"
    fi
  else
    # File doesn't exist - create from example
    if [[ -f "$TFVARS_EXAMPLE" ]]; then
      cp "$TFVARS_EXAMPLE" "$tfvars"
      # Uncomment and set hcloud_image_id
      sed -i "s/^[[:space:]]*#*[[:space:]]*hcloud_image_id.*/hcloud_image_id = $image_id/" "$tfvars"
      echo "==> Created $tfvars from example with hcloud_image_id = $image_id"
    else
      # No example file - create minimal tfvars
      cat > "$tfvars" << EOF
# Auto-generated by upload-image.sh
# See terraform.tfvars.example for all available options

hcloud_image_id = $image_id

# Required: Uncomment and set these values
# hcloud_token = "your-hcloud-token"
# flakehub_token = "your-flakehub-token"
# deploy_ssh_public_key = "ssh-ed25519 AAAA..."

flake_reference = "outskirtslabs/nixos-hetzner-demo/0.1#nixosConfigurations.ethercalc-demo"
server_type = "cx22"
location = "fsn1"
EOF
      echo "==> Created $tfvars with hcloud_image_id = $image_id"
    fi
  fi
}

update_tfvars "$IMAGE_ID" "$TFVARS_FILE"

echo ""
echo "Next steps:"
echo "  1. Edit $TFVARS_FILE to set required values (tokens, SSH keys)"
echo "  2. cd setup && tofu init && tofu apply"
